# Generated by Django 5.0.1 on 2024-02-16 14:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100, verbose_name='نام')),
                ('l_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=14, unique=True, verbose_name='شماره تلفن')),
                ('linkedin', models.CharField(max_length=250, verbose_name='آدرس لینکدین')),
                ('telegram', models.CharField(max_length=250, verbose_name='تلگرام')),
                ('instagram', models.CharField(max_length=250, verbose_name='اینستاگرام')),
                ('github', models.CharField(max_length=250, verbose_name='آدرس گیتهاب')),
                ('about_me', ckeditor.fields.RichTextField(verbose_name='درباه من(نمایش در بخش درباه من)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Account/images', verbose_name='تصویر پروفایل')),
            ],
            options={
                'verbose_name': 'اطلاعات من',
                'verbose_name_plural': 'اطلاعات من',
            },
        ),
    ]
