# Generated by Django 5.0.1 on 2024-01-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('f_name', models.CharField(max_length=100, verbose_name='نام')),
                ('l_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=14, verbose_name='شماره تلفن')),
                ('linkdin', models.CharField(max_length=250, verbose_name='آدرس لینکدین')),
                ('telegram', models.CharField(max_length=250, verbose_name='تلگرام')),
                ('github', models.CharField(max_length=250, verbose_name='آدرس گیتهاب')),
                ('iamge', models.ImageField(blank=True, null=True, upload_to='Account/images', verbose_name='تصویر پروفایل')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
