# Generated by Django 5.0.1 on 2024-02-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published',
            field=models.BooleanField(default=False, verbose_name='وضعیت انتشار'),
        ),
    ]
