# Generated by Django 5.0.1 on 2024-01-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_remove_category_article_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='Article.category', verbose_name='دسته بندی'),
        ),
    ]
