# Generated by Django 5.0.1 on 2024-02-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_comment_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='color',
            field=models.CharField(default='Red', max_length=20),
        ),
    ]
