# Generated by Django 5.0.1 on 2024-03-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0005_alter_article_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
