# Generated by Django 5.0.1 on 2024-01-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0006_alter_article_body_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
