# Generated by Django 5.0.1 on 2024-03-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0007_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ انتشار'),
        ),
    ]
