# Generated by Django 5.0.1 on 2024-03-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0008_category_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=False, verbose_name='وضعیت انتشار'),
        ),
        migrations.AddField(
            model_name='category',
            name='published',
            field=models.BooleanField(default=False, verbose_name='وضعیت انتشار'),
        ),
    ]
