# Generated by Django 5.0.1 on 2024-03-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftNavbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('emage', models.ImageField(upload_to='Index/images', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'تصویر تبلیغاتی left navbar',
                'verbose_name_plural': 'تصاویر تبلیغاتی left navbar',
            },
        ),
    ]
